language: r

warnings_are_errors: false

before_install:
  - tlmgr install babel babel-german

cache:
  packages: true
  directories:
    - $TRAVIS_BUILD_DIR/_bookdown_files

addons:
  apt:
    packages:
      - pdf2svg
      - libudunits2-dev

script:
  - Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::gitbook')"
  - Rscript -e "bookdown::render_book('index.Rmd', 'bookdown::pdf_book')"
  - mkdir cards
  - Rscript rendercards.R

deploy:
  - provider: pages
    github_token: $GITHUB_PAT
    local_dir: _book/
    skip_cleanup: true
    on:
      branch: master

notifications:
  email: false
