language: r

sudo: false

warnings_are_errors: false

repos:
  MRAN: "https://mran.microsoft.com/snapshot/2017-02-06"

r_github_packages:
  - maxheld83/pensieve
  - maxheld83/qmethod

cache:
  packages: true

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh

notifications:
  email: false
