---
title: 'Q-Labouratory: Eine Q-Studie zur Subjektivität der Arbeit (Pretest)'
author: "Sabine Pfeiffer, Sandra Kawalec und Maximilian Held"
date: "15 July 2016"
output: pdf_document
---

# Studienanleitung (Condition of Instruction)

Vielen Dank, dass Sie an unserer Studie über die Subjektivität zur Arbeit teilnehmen.

<!-- Bitte klicken Sie auf den "Fortsetzen"-Button. -->

Stellen Sie sich vor, Sie treffen sich in einige Jahre nach ihrem Abschluss erneut mit ihren Kommilitoninnen und Kommilitonen.
Sie kommen ins Gespräch, und reflektieren über ihre zukünftige Arbeit.

Bitte beantworten Sie uns in dieser fiktiven Situation **zwei Fragen**, in dieser Reihenfolge:

- a) Was *möchten* Sie dann über ihre Arbeit sagen können?
- b) Was *werden* Sie *wahrscheinlich* über ihre Arbeit sagen können?

Sortieren Sie die folgenden Aussagen danach, wie sehr auf ihre fiktive zukünftive Einschätzung ihrer Arbeit zutreffen.


<!-- Bitte gehen Sie dabei wie folgt vor: -->

<!-- 1. Lesen Sie alle Karten einmal durch. -->
<!-- 2. Sortieren Sie die Karten grob in drei Kategorien. -->
<!-- 	Die Kategorien müssen *nicht* gleich groß sein. -->
<!-- 	1. Karten, dessen Inhalt Sie eher für unzutreffend halten, legen Sie auf einem Stapel rechts von der Schablone ab. -->
<!-- 	2. Karten, dessen Inhalt Sie eher für zutreffend halten, legen Sie auf einen Stapel links von der Schablone ab. -->
<!-- 	3. Karten, dessen Inhalt Sie neutral gegenüberstehen, widersprüchliche Reaktionen haben oder die Sie nicht verstehen legen Sie vor Ihnen über der Schablone ab. -->
<!-- 3. Konzentrieren Sie sich auf die Karten aus Kategorie **a**.  -->
<!-- 	Sortieren Sie die Karten nach dem Grad ihrer Zustimmung. -->
<!-- 	Beginnen Sie mit den Karten, denen Sie am meisten zustimmen und belegen Sie entsprechend die Felder vom rechten Rand der Schablone ausgehend. -->
<!-- 4. Wenn Sie mit den Karten der Kategorie **a** fertig sind, tragen Sie die Umrisse der ausgefüllten Felder in die beiliegende Tabelle ein. -->
<!-- 5. Machen Sie mit den Karten aus Kategorie **b** weiter. -->
<!-- 	Verfahren Sie wie in Schritt 3; beginnend mit den Karten deren Inhalt Sie am meisten ablehnen. -->
<!-- 	Belegen Sie mit diesen die Felder ausgehend vom linken Rand der Schablone. -->
<!-- 6. Tragen Sie erneut die entstandenen Umrisse in die beiliegende Tabelle ein. -->
<!-- 7. Verteilen Sie die verbleibenden Karten aus Kategorie **c** auf die leeren Felder entsprechend Ihrem Grad der Zustimmung. -->
<!-- 8. Kontrollieren Sie noch einmal die Verteilung aller Karten und nehmen Sie bei Bedarf Änderungen vor. -->
<!-- 9. Notieren Sie die Position der Karten anhand der Kennungen (etwa: `C21`) in der beiligenden Tabelle und benachrichtigen Sie den Umfrageleiter. -->


Bitte beachten Sie dabei:

- Es gibt *keine richtigen oder falschen Sortierungen*.
	Ihre subjektive Einstellung und Interpretation zu den Aussagen auf den Karten zählt.
- Wenn Sie ein Item nicht verstehen, es Ihnen sinnlos erscheint oder Sie der Aussage ambivalent gegenüber stehen, sortieren Sie *zwischen* ihre positiven (zutreffenden) und negativen (nicht zutreffenden) Items oder über den Nullpunkt in der Mitte.
  In beiden Fällen werden wir Ihre Sortierung entsprechend in der Analyse berücksichtigen.
  Auch wenn Sie zu einem Item *keine* klare Einstellung haben, ist das für uns eine wichtige Information und Ausdruck Ihrer legitimen Subjektivität.
- Der Nullpunkt auf der Schablone ist bedeutungslos.
	Der Wert **–1** muss etwa nicht heißen, dass Sie einer dort gelegten Karte widersprechen; es deutet lediglich an, dass sie einer dort gelegten Karte *weniger* zustimmen als einer bei **0** gelegten Karte.
	Nur *relative* Positionen der Karten zählen.
- Nur die horizontale Position (von links nach rechts) der Karten ist bedeutsam.
	Die vertikale Position (von oben oder unten) innerhalb einer Spalte sagt nichts aus.
- Alle Karten müssen gelegt werden, und alle Felder belegt.
- Notieren Sie sich jederzeit Anmerkungen oder Ergänzungen zu den einzelnen Karten, auf dem separaten Feedback-Bogen.
- Sie können unten stehend auch eigene Aussagen für zukünftige Q-Sortierungen vorschlagen.
	Diese neuen Karten können Sie allerdings dieses Mal noch nicht in der Sortierung berücksichtigen.

Bitte gehen Sie nun auf die Website **`http://labouratory.de/qsort`** um an der Erhebung teilzunehmen.

\newpage

## Eigene Vorschläge für Items


### Durchgang A Positiv

Bitte nennen Sie uns ein fehlendes Item, dass Sie für *wünschenswert* gehalten hätten.
(Also ein Item, das im Durchgang a) ganz rechts gelegen hätte).

\vspace{70pt}

### Durchgang A Negativ

Bitte nennen Sie uns ein fehlendes Item, dass Sie für *nicht wünschenswert* gehalten hätten.
(Also ein Item, das im Durchgang a) ganz links gelegen hätte).

\vspace{70pt}

### Durchgang B Positiv

Bitte nennen Sie uns ein fehlendes Item, dass Sie für *wahrscheinlich* gehalten hätten.
(Also ein Item, das im Durchgang b) ganz rechts gelegen hätte).

\vspace{70pt}

### Durchgang B Negativ

Bitte nennen Sie uns ein fehlendes Item, dass Sie für *nicht wahrscheinlich* gehalten hätten.
(Also ein Item, das im Durchgang b) ganz links gelegen hätte).

\vspace{70pt}
